In [1]:
import matplotlib.pyplot as plt
from sklearn.neighbors import KNeighborsClassifier
import pandas as pd
import numpy as np
import os

In [2]:
NYC_df = pd.read_csv("NYC_df_1_5_19.csv")
NYC_df.head()

,LAT,LONG,Manhattan,Brooklyn,Bronx,Queens,StatenIsland,DrivInattDistr,FailYield,FollowClose,...,Wednesday,Thursday,Friday,Saturday,Sunday,Fri_or_SatNight,Spring,Summer,Fall,Winter
0,40.781690,-73.94897,1,0,0,0,0,0,0,1,...,0,0,1,0,0,0,0,0,1,0
1,40.620872,-74.00221,0,1,0,0,0,0,1,0,...,0,1,0,0,0,0,0,0,1,0
2,40.749890,-73.86259,0,0,0,1,0,0,0,0,...,0,1,0,0,0,0,0,0,1,0
3,40.716140,-73.83357,0,0,0,1,0,0,0,0,...,0,1,0,0,0,0,0,0,1,0
4,40.610115,-73.98489,0,1,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,1,0

In [3]:
NYC_df.count()

LAT                       51360
LONG                      51360
Manhattan                 53356
Brooklyn                  53356
Bronx                     53356
Queens                    53356
StatenIsland              53356
DrivInattDistr            53356
FailYield                 53356
FollowClose               53356
BackUnsafe                53356
UnsafeLaneChange          53356
PassLaneUseImprop         53356
TrafControlDisregard      53356
UnsafeSpeed               53356
TurnImprop                53356
AggrDrive                 53356
FailKeepRight             53356
UnsafeDriving             53356
RecklessDriving           53356
collis_sedan_sedan        53356
collis_sedan_SWorSUV      53356
collis_SWorSUV_SWorSUV    53356
Motorist_Inj_Dead         53356
MorningRush               53356
Midday                    53356
EveningRush               53356
Overnight                 53356
Monday                    53356
Tuesday                   53356
Wednesday                 53356
Thursday                  53356
Friday                    53356
Saturday                  53356
Sunday                    53356
Fri_or_SatNight           53356
Spring                    53356
Summer                    53356
Fall                      53356
Winter                    53356
dtype: int64

In [4]:
cols_to_drop=['LAT','LONG','Brooklyn','Bronx','Queens','StatenIsland',
              'DrivInattDistr','UnsafeLaneChange','PassLaneUseImprop',
              'TurnImprop','collis_sedan_sedan','MorningRush',
              'EveningRush','Midday','Overnight','Friday','Saturday',
              'Sunday','Monday','Tuesday','Wednesday','Winter',
              'Spring','Fall']
NYC_df=NYC_df.drop(columns=cols_to_drop)

In [5]:
NYC_df.count()

Manhattan                 53356
FailYield                 53356
FollowClose               53356
BackUnsafe                53356
TrafControlDisregard      53356
UnsafeSpeed               53356
AggrDrive                 53356
FailKeepRight             53356
UnsafeDriving             53356
RecklessDriving           53356
collis_sedan_SWorSUV      53356
collis_SWorSUV_SWorSUV    53356
Motorist_Inj_Dead         53356
Thursday                  53356
Fri_or_SatNight           53356
Summer                    53356
dtype: int64

In [6]:
cols_to_drop=['FailYield','Thursday','AggrDrive',
              'FailKeepRight','Manhattan']
NYC_df=NYC_df.drop(columns=cols_to_drop)

In [7]:
NYC_df['Outcome']=NYC_df['Motorist_Inj_Dead']

In [8]:
NYC_df.dtypes

FollowClose               int64
BackUnsafe                int64
TrafControlDisregard      int64
UnsafeSpeed               int64
UnsafeDriving             int64
RecklessDriving           int64
collis_sedan_SWorSUV      int64
collis_SWorSUV_SWorSUV    int64
Motorist_Inj_Dead         int64
Fri_or_SatNight           int64
Summer                    int64
Outcome                   int64
dtype: object

In [9]:
X = NYC_df.iloc[:, :5].values
Y = NYC_df.iloc[:, 6].values

In [10]:
target = NYC_df["Motorist_Inj_Dead"]
target_names = ["No_harm","Injured_or_dead"]
X

array([[1, 0, 0, 0, 1],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 1],
       ...,
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [1, 0, 0, 0, 1]], dtype=int64)

In [11]:
NYC_df=NYC_df.drop("Summer",axis=1)

data = NYC_df.drop("Motorist_Inj_Dead", axis=1)
feature_names = data.columns
data.head()

,FollowClose,BackUnsafe,TrafControlDisregard,UnsafeSpeed,UnsafeDriving,RecklessDriving,collis_sedan_SWorSUV,collis_SWorSUV_SWorSUV,Fri_or_SatNight,Outcome
0,1,0,0,0,1,0,0,0,0,0
1,0,0,0,0,1,0,0,0,0,0
2,0,0,0,0,1,0,1,0,0,0
3,0,0,1,0,0,1,0,0,0,0
4,0,1,0,0,1,0,1,0,0,0

In [12]:
feature_names

Index(['FollowClose', 'BackUnsafe', 'TrafControlDisregard', 'UnsafeSpeed',
       'UnsafeDriving', 'RecklessDriving', 'collis_sedan_SWorSUV',
       'collis_SWorSUV_SWorSUV', 'Fri_or_SatNight', 'Outcome'],
      dtype='object')

In [13]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, 
                                   random_state=42,test_size=.1)

In [14]:
# Support vector machine linear classifier
from sklearn.svm import SVC 
model = SVC(kernel='linear',class_weight='balanced')
model.fit(X_train, y_train)

SVC(C=1.0, cache_size=200, class_weight='balanced', coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [15]:
# Model Accuracy
print('Test Acc: %.3f' % model.score(X_test, y_test))

Test Acc: 0.576

In [16]:
# Calculate classification report
from sklearn.metrics import classification_report
predictions = model.predict(X_test)
print(classification_report(y_test, predictions,
                            target_names=target_names))

                 precision    recall  f1-score   support

        No_harm       0.79      0.62      0.69      4110
Injured_or_dead       0.26      0.44      0.32      1226

    avg / total       0.67      0.58      0.61      5336

In [17]:
NYC_df.describe()

,FollowClose,BackUnsafe,TrafControlDisregard,UnsafeSpeed,UnsafeDriving,RecklessDriving,collis_sedan_SWorSUV,collis_SWorSUV_SWorSUV,Motorist_Inj_Dead,Fri_or_SatNight,Outcome
count,53356.000000,53356.000000,53356.000000,53356.000000,53356.000000,53356.000000,53356.000000,53356.000000,53356.000000,53356.000000,53356.000000
mean,0.111309,0.112621,0.036360,0.017411,0.494040,0.099651,0.230546,0.595285,0.140153,0.064266,0.140153
std,0.314517,0.316132,0.187185,0.130800,0.499969,0.299537,0.421186,0.490842,0.347149,0.245229,0.347149
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000
75%,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000